### ISSUE TITLE
Instructions unclear, 

### ISSUE THREAD

**Issue by boapps** [theriley106/Nightchord#4]
Hey! Interesting project, nice to see you're active again, but I can't really get it to work.
I got the apiKey and installed all dependencies, but when I start `python2 app.py` and open `http://localhost:5000/download/?artist=avicii&song=wake%20me%20up` I get the following:
ERROR PLEASE TRY AGAIN LATER
Am I missing something, or is this still a work in progress?

**Comment by boapps** [comment]
Also the console shows: `ERROR ON LOADING`

**Comment by theriley106** [comment]
Hey boapps!  Thanks for checking out the project!  I just pushed some changes a few minutes ago that should give you a more verbose error if you run into an issue with the web app.  Would you mind pulling those changes and sending me the error you're getting?

I also added a shell script called ```simple.sh``` and a python script called ```simple.py``` that isolates all of the audio generation functions.  If you run ```./simple.sh``` it should let you generate music from the command line without the web app.  

Thanks again for trying this out, and if you run into any issues please let me know and I can try to fix them ASAP.

**Comment by boapps** [comment]
Thanks for the quick update!
Here is my new error :)
```[boa@boa-laptop Nightchord]$ python2 simple.py

_____ NIGHTCORE GENERATOR ______

Artist: Owl city
Song: Good time
Traceback (most recent call last):
  File "simple.py", line 89, in <module>
    createYoutubeCLI(artist, song)
  File "simple.py", line 76, in createYoutubeCLI
    URL = findSong(val['artist'], val['song'])
  File "simple.py", line 70, in findSong
    return genYoutube('{} {} lyrics'.format(artist, song))
  File "simple.py", line 65, in genYoutube
    VideoID = str(Results[0].select('.overflow-menu-choice')[0]).partition('data-video-ids="')[2].partition('" onclick="')[0]
IndexError: list index out of range
```

**Comment by boapps** [comment]
Oh I know why the error, I live in Hungary and the youtube page, that you try to parse is in hungarian and it doesn't contain the string 'Duration'.

**Comment by boapps** [comment]
Ok, I fixed the previous error by replacing the string 'Duration' with it's Hungarian translation, but now I'm getting a different error.

```
[boa@boa-laptop Nightchord]$ python2 simple.py

_____ NIGHTCORE GENERATOR ______

Artist: Avicii
Song: Wake me up
[youtube] yVjjuOqMQIw: Downloading webpage
[youtube] yVjjuOqMQIw: Downloading video info webpage
[download] Destination: Avicii_Wake_me_up.f398
[download] 100% of 5.18MiB in 00:0144MiB/s ETA 00:00known ETA
[download] Destination: Avicii_Wake_me_up.f140
[download] 100% of 3.86MiB in 00:0080MiB/s ETA 00:004
[ffmpeg] Merging formats into "Avicii_Wake_me_up.mp4"
Deleting original file Avicii_Wake_me_up.f398 (pass -k to keep)
Deleting original file Avicii_Wake_me_up.f140 (pass -k to keep)
Traceback (most recent call last):
  File "simple.py", line 89, in <module>
    createYoutubeCLI(artist, song)
  File "simple.py", line 80, in createYoutubeCLI
    a = ExtractAudio('{}.mp4'.format(filename))
  File "simple.py", line 47, in ExtractAudio
    video = VideoFileClip(filename.replace(".mp4", "") + ".mp4")
  File "/usr/lib/python2.7/site-packages/moviepy/video/io/VideoFileClip.py", line 91, in __init__
    fps_source=fps_source)
  File "/usr/lib/python2.7/site-packages/moviepy/video/io/ffmpeg_reader.py", line 73, in __init__
    self.lastread = self.read_frame()
  File "/usr/lib/python2.7/site-packages/moviepy/video/io/ffmpeg_reader.py", line 139, in read_frame
    self.filename))
IOError: MoviePy error: failed to read the first frame of video file Avicii_Wake_me_up.mp4. That might mean that the file is corrupted. That may also mean that you are using a deprecated version of FFMPEG. On Ubuntu/Debian for instance
the version in the repos is deprecated. Please update to a recent version from the website.

```

Since the debug message suggests, that the error is because of my ffmpeg installation, here is the output of `ffmpeg`:
```
[boa@boa-laptop Nightchord]$ ffmpeg
ffmpeg version n4.2 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 9.1.0 (GCC)
  configuration: --prefix=/usr --disable-debug --disable-static --disable-stripping --enable-fontconfig --enable-gmp --enable-gnutls --enable-gpl --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libdav1d --enable-libdrm --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libiec61883 --enable-libjack --enable-libmodplug --enable-libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxcb --enable-libxml2 --enable-libxvid --enable-nvdec --enable-nvenc --enable-omx --enable-shared --enable-version3
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
Hyper fast Audio and Video encoder
usage: ffmpeg [options] [[infile options] -i infile]... {[outfile options] outfile}...

Use -h to get full help or, even better, run 'man ffmpeg'

```

**Comment by boapps** [comment]
Okey, I don't know what my problem was, but now it's fixed and now that it works, god damn, it's amazing!
